---
- name: Install apt-transport-https package
  apt:
    name: apt-transport-https
    state: present

- name: Add Nodesource apt key
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: Add NodeSource repos
  apt_repository:
    repo: "{{item}}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{nodejs_version}} {{ansible_distribution_release}} main"
    - "deb-src https://deb.nodesource.com/node_{{nodejs_version}} {{ansible_distribution_release}} main"
  register: node_repo

- name: Install Node.js and npm packages
  apt:
    name: "nodejs={{nodejs_version|regex_replace('x', '')}}*"
    state: present
    update_cache: yes

- name: Create npm global directory
  file:
    path: "{{npm_config_prefix}}"
    owner: "{{npm_user}}"
    group: "{{npm_user}}"
    state: directory

- name: Add npm_config_prefix bin directory to global $PATH.
  template:
    src: npm.sh.j2
    dest: /etc/profile.d/npm.sh
    mode: 0644

- name: Ensure npm global packages are installed.
  npm:
    name: "{{item.name | default(item)}}"
    version: "{{item.version | default('latest')}}"
    global: true
    state: latest
  environment:
    NPM_CONFIG_PREFIX: "{{npm_config_prefix}}"
    NODE_PATH: "{{npm_config_prefix}}/lib/node_modules"
    NPM_CONFIG_UNSAFE_PERM: "{{npm_config_unsafe_perm}}"
  with_items: "{{nodejs_npm_global_packages}}"
  tags: ['skip_ansible_lint']

- name: Install packages defined in a given package.json.
  npm:
    path: "{{nodejs_package_json_path}}"
  when: nodejs_package_json_path is defined and nodejs_package_json_path
